services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped  #Docker automatically restarts it if it crashes or the machine reboots.
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v3.13.3
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml

# Your host                         Prometheus container

# ./prometheus.yml ──────────────→ /etc/prometheus/prometheus.yml

# Prometheus reads your configuration from there.

      - prometheus_storage:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"


  node-exporter:
    image: prom/node-exporter:v1.12.1
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro  #ro:read-only
      - /sys:/host/sys:ro #HOST PATH : CONTAINER PATH : MODE
      - /:/rootfs:ro
# HOST                         CONTAINER

# /proc  ────────────────→    /host/proc
# /sys   ────────────────→    /host/sys
# /      ─────────────────→    /rootfs
    command:
      - '--path.procfs=/host/proc'  #Use this directory as the proc filesystem not the container's.
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

volumes:
  grafana_storage: 
  prometheus_storage: